language: node_js
node_js:
  - "9"
script: gulp --youtube $YOUTUBE_API_KEY --vimeo $VIMEO_API_KEY
after_success: ./deploy-ghpages.sh
env:
  global:
    - TARGET_BRANCH="gh-pages"
    - MASTER_BRANCH="master"
    - SOURCE_DIR="dist"
    - PUBLISH_DIR=".publish"